secret_key_base: keqqLSJvSqMpJkfndEQK83AylO4bMayJF72cIc1Ap7w
port: 3000
name: amber-moon

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
    
host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:password@localhost:5432/amber_moon_test
auto_reload: false

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
